### ISSUE TITLE
Thumbnail isn't generated when editing a post

### ISSUE THREAD

**Issue by kartikluke** [TelescopeJS/Telescope-Module-Embedly#8]
I have some old posts from before I added the embedly API key. But I'm not able to generate thumbnails, even when I change the URL.

**Comment by SachaG** [comment]
The next Telescope release adds a "regenerate thumbnail" button :)

By the way, this repo is for the code in the Embedly tutorial, which is now actually pretty different from the code actually used in Telescope. Just thought I'd point this out.

**Comment by kartikluke** [comment]
Alright thanks. When can we expect the new version of Telescope? And I assume the embedly code is in the TelescopeJS repo itself.

**Comment by SachaG** [comment]
I just want to keep testing it a bit for a couple more days before I
release it :) And yes, the embedly code is in the repo.

On Sat, Jan 24, 2015 at 2:45 PM, Kartik Luke Singh <notifications@github.com
